GLTV/Models/Objects/Filter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GLTV.Models.Objects
{
    public class Filter
    {
        public int ID { get; set; }
        [Required]
        public FilterType FilterType { get; set; }
        [Required]
        public FilterCategory FilterCategory { get; set; }
        [Required]
        public string Value { get; set; }
    }

    public enum FilterType
    {
        Type = 1,
        Category = 2,
        Location = 3
    }
    public enum FilterCategory
    {
        All = 0,
        Reality = 1
    }
}

GLTV/Controllers/InzeratyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GLTV.Models.Objects;
using GLTV.Models.ViewModels;
using GLTV.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GLTV.Controllers
{
    [Authorize]
    public class InzeratyController : Controller
    {
        private readonly IInzeratyService _inzeratyService;
        private readonly IUserService _userService;

        public InzeratyController(IInzeratyService inzeratyService, IUserService userService)
        {
            _inzeratyService = inzeratyService;
            _userService = userService;
        }

        public async Task<IActionResult> Index(string inzeratType, string inzeratCategory, string location, string priceString, int? pageNumber)
        {
            FilterData filterData = new FilterData();
            int priceMax = 0;

            if (string.IsNullOrEmpty(inzeratCategory) && string.IsNullOrEmpty(inzeratType) &&
                string.IsNullOrEmpty(location) && string.IsNullOrEmpty(priceString))
            {
                // if no filter, load user's filter data
                filterData = await _userService.FetchUserFilterDataAsync();
                Int32.TryParse(filterData.PriceString, out priceMax);
            }
            else
            {
                // parse filter data from request and save in DB
                filterData.InzeratCategory = inzeratCategory;
                filterData.InzeratType = inzeratType;
                filterData.Location = location;
                Int32.TryParse(priceString, out priceMax);
                filterData.PriceString = priceMax.ToString();

                await _userService.UpdateUserFilterDataAsync(filterData);
            }

            int pageSize = 100;
            var model = new InzeratyViewModel();


            model.Inzeraty = await _inzeratyService.FetchInzeratyAsync(
                filterData.InzeratType,
                filterData.InzeratCategory,
                filterData.Location,
                priceMax,
                pageNumber ?? 1,
                pageSize);

            model.InzeratyTypes = new SelectList(await _inzeratyService.FetchInzeratyTypesAsync());
            model.InzeratyCategories = new SelectList(await _inzeratyService.FetchInzeratyCategoriesAsync());
            model.Locations = new SelectList(await _inzeratyService.FetchInzeratyLocationsAsync());
            model.InzeratType = filterData.InzeratType;
            model.InzeratCategory = filterData.InzeratCategory;
            model.Location = filterData.Location;
            model.PriceString = filterData.PriceString;

            return View(model);
        }

        public async Task<IActionResult> Marked(string inzeratType, string inzeratCategory, string location, string priceString, int? pageNumber)
        {
            FilterData filterData = new FilterData();
            int priceMax = 0;

            // parse filter data from request and save in DB
            filterData.InzeratCategory = inzeratCategory;
            filterData.InzeratType = inzeratType;
            filterData.Location = location;
            Int32.TryParse(priceString, out priceMax);
            filterData.PriceString = priceMax.ToString();

            int pageSize = 100;
            var model = new InzeratyViewModel();
            
            model.Inzeraty = await _inzeratyService.FetchMarkedInzeratyAsync(
                filterData.InzeratType,
                filterData.InzeratCategory,
                filterData.Location,
                priceMax,
                pageNumber ?? 1,
                pageSize);

            model.InzeratyTypes = new SelectList(await _inzeratyService.FetchInzeratyTypesAsync());
            model.InzeratyCategories = new SelectList(await _inzeratyService.FetchInzeratyCategoriesAsync());
            model.Locations = new SelectList(await _inzeratyService.FetchInzeratyLocationsAsync());
            model.InzeratType = filterData.InzeratType;
            model.InzeratCategory = filterData.InzeratCategory;
            model.Location = filterData.Location;
            model.PriceString = filterData.PriceString;

            return View(model);
        }

        public async Task<IActionResult> Ignored(string inzeratType, string inzeratCategory, string location, string priceString, int? pageNumber)
        {
            FilterData filterData = new FilterData();
            int priceMax = 0;

            // parse filter data from request and save in DB
            filterData.InzeratCategory = inzeratCategory;
            filterData.InzeratType = inzeratType;
            filterData.Location = location;
            Int32.TryParse(priceString, out priceMax);
            filterData.PriceString = priceMax.ToString();

            int pageSize = 100;
            var model = new InzeratyViewModel();

            model.Inzeraty = await _inzeratyService.FetchIgnoredInzeratyAsync(
                filterData.InzeratType,
                filterData.InzeratCategory,
                filterData.Location,
                priceMax,
                pageNumber ?? 1,
                pageSize);

            model.InzeratyTypes = new SelectList(await _inzeratyService.FetchInzeratyTypesAsync());
            model.InzeratyCategories = new SelectList(await _inzeratyService.FetchInzeratyCategoriesAsync());
            model.Locations = new SelectList(await _inzeratyService.FetchInzeratyLocationsAsync());
            model.InzeratType = filterData.InzeratType;
            model.InzeratCategory = filterData.InzeratCategory;
            model.Location = filterData.Location;
            model.PriceString = filterData.PriceString;

            return View(model);
        }
    }
}

GLTV/Controllers/LogEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GLTV.Models.ViewModels;
using GLTV.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GLTV.Controllers
{
    [Authorize]
    public class LogEventController : Controller
    {
        private readonly ILogEventService _logEventService;

        public LogEventController(ILogEventService logEventService)
        {
            _logEventService = logEventService;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            LogEventViewModel model = new LogEventViewModel();
            model.LogEvents = await _logEventService.FetchScraperLogEventsAsync(pageNumber ?? 1);

            return View(model);
        }
    }
}

GLTV/Views/Shared/_FilterForm.cshtml
@model GLTV.Models.ViewModels.InzeratyViewModel

<div class="form-group">
    <label for="InzeratType">Typ:</label>
    <select asp-for="InzeratType" asp-items="Model.InzeratyTypes">
        <option>All</option>
    </select>
</div>
<div class="form-group">
    <label for="InzeratCategory">Kategória:</label>
    <select asp-for="InzeratCategory" asp-items="Model.InzeratyCategories">
        <option>All</option>
    </select>
</div>
<div class="form-group">
    <label for="Location">Lokácia:</label>
    <select asp-for="Location" asp-items="Model.Locations">
        <option>All</option>
    </select>
</div>
<div class="form-group">
    <label for="PriceString">Cena do:</label>
    <input type="number" asp-for="PriceString" />
</div>
<button type="submit" class="btn btn-default">Filtrovať</button>

GLTV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - scraper.sk</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link rel="stylesheet" href="/css/bootstrap-datetimepicker.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/css/bootstrap-slider.min.css" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script type="text/javascript" src="/js/moment-with-locales.js"></script>
    <script type="text/javascript" src="/js/bootstrap-datetimepicker.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <!-- piexif.min.js is only needed for restoring exif data in resized images and when you
        wish to resize images before upload. This must be loaded before fileinput.min.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/piexif.min.js" type="text/javascript"></script>
    <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
        This must be loaded before fileinput.min.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/sortable.min.js" type="text/javascript"></script>
    <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for
        HTML files. This must be loaded before fileinput.min.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/purify.min.js" type="text/javascript"></script>
    <!-- the main fileinput plugin file -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/fileinput.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/locales/LANG.js"></script>*@

    <link rel="stylesheet" href="/css/blueimp-gallery.min.css">
    <script src="/js/blueimp-gallery.min.js"></script>
    <script src="/js/jquery.blockUI.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/bootstrap-slider.min.js"></script>

    @RenderSection("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Inzeraty" asp-action="Index" class="navbar-brand">scraper.sk</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="@(ViewBag.IndexNav == true ? "active-underline" : "")"><a asp-area="" asp-controller="Inzeraty" asp-action="Index">Inzeráty</a></li>
                    <li class="@(ViewBag.MarkedNav == true ? "active-underline" : "")"><a asp-area="" asp-controller="Inzeraty" asp-action="Marked">Poznačené</a></li>
                    <li class="@(ViewBag.IgnoredNav == true ? "active-underline" : "")"><a asp-area="" asp-controller="Inzeraty" asp-action="Ignored">Ignorované</a></li>
                    <li class="@(ViewBag.LogNav == true ? "active-underline" : "")"><a asp-area="" asp-controller="LogEvent" asp-action="Index">Log</a></li>
                    @*<li class="@(ViewBag.ClientNav == true ? "active-underline" : "")"><a asp-area="" asp-controller="Utility" asp-action="ActiveScreens">Active Screens</a></li>
        <li class="@(ViewBag.HelpNav == true ? "active-underline" : "")"><a asp-area="" asp-controller="Utility" asp-action="Help">Help</a></li>*@
                    @*<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - scraper.sk</p>
        </footer>
    </div>
</body>
</html>